# Generated by Django 4.0.6 on 2022-07-24 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dget', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoDump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('data', models.JSONField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Statistic',
        ),
        migrations.AlterField(
            model_name='greeting',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
